name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t <your-image-name> .

      - name: Tag Docker image
        run: |
          docker tag <your-image-name>:latest <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/<your-image-name>:latest

      - name: Push Docker image to ECR
        run: |
          docker push <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/<your-image-name>:latest
